[package]
name = "mff-hr-v1"
version = "0.1.0"
authors = ["nullstalgia <nullstalgia@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "mff-hr-v1"
harness = false    # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = ["std", "embassy", "esp-idf-svc/native"]

pio = ["esp-idf-svc/pio"]
std = ["alloc", "esp-idf-svc/binstart", "esp-idf-svc/std"]
alloc = ["esp-idf-svc/alloc"]
nightly = ["esp-idf-svc/nightly"]
experimental = ["esp-idf-svc/experimental"]
embassy = [
    "esp-idf-svc/embassy-sync",
    "esp-idf-svc/critical-section",
    "esp-idf-svc/embassy-time-driver",
]


[dependencies]
log = "0.4"
esp-idf-svc = { version = "0.49", default-features = false }
esp-idf-hal = { version = "0.44", default-features = false }
esp-idf-sys = { version = "0.35", default-features = false }
esp32-nimble = "0.8.2"
anyhow = "1.0.93"
bstr = "1.11.0"
embedded-graphics = "0.8.1"
# ili9341 = "0.6.0"
display-interface = "0.5.0"
display-interface-spi = "0.5.0"
embedded-hal = "1.0.0"
mipidsi = "0.8.0"

[build-dependencies]
embuild = { version = "0.32.0", features = ["espidf"] }
cc = "=1.1.30"                                          # Necessary until a new version of `esp-idf-sys` is released
