name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build
            args: --release
          # - command: fmt
          # args: --all -- --check --color always
          # - command: clippy
          #   args: --all-targets --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Submodule Init
        uses: snickerbockers/submodules-init@v4
      - name: Setup esp-rs/xtensa Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32
          ldproxy: true
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      # - name: Patch idf-svc
      # run: cargo run --manifest-path ./cargo-patch-crate-fork/Cargo.toml --target x86_64-unknown-linux-gnu
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
      - name: Install Linux Dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
        continue-on-error: true
      - name: Setup Linux Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
        continue-on-error: true
      - name: Convert ELF to .bin
        run: |
          cargo install espflash --version 3.2.0 --target x86_64-unknown-linux-gnu
          ~/.cargo/bin/espflash save-image --chip esp32 target/xtensa-esp32-espidf/release/mff-hr-v1 target/xtensa-esp32-espidf/release/app.bin
          ~/.cargo/bin/espflash partition-table partitions.csv --to-binary -o target/xtensa-esp32-espidf/release/partitions-0x8000.bin
        continue-on-error: true
      - name: Archive Release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            target/xtensa-esp32-espidf/release/build/esp-idf-sys-**/out/build/bootloader/bootloader.bin
            target/xtensa-esp32-espidf/release/mff-hr-v1
            target/xtensa-esp32-espidf/release/app.bin
            target/xtensa-esp32-espidf/release/partitions-0x8000.bin
